# Generated by Django 6.0.1 on 2026-01-15 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('assessments', '0001_initial'),
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='academic.curriculum')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Strand',
                'verbose_name_plural': 'Strands',
                'ordering': ['curriculum', 'subject', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='SubStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_strands', to='cbc.strand')),
            ],
            options={
                'verbose_name': 'Sub-Strand',
                'verbose_name_plural': 'Sub-Strands',
                'ordering': ['strand', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('level', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='cbc.substrand')),
            ],
            options={
                'verbose_name': 'Learning Outcome',
                'verbose_name_plural': 'Learning Outcomes',
                'ordering': ['sub_strand', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('evaluation_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('RUBRIC', 'Rubric'), ('DESCRIPTIVE', 'Descriptive'), ('COMPETENCY', 'Competency')], max_length=20)),
                ('numeric_score', models.FloatField(blank=True, null=True)),
                ('narrative', models.TextField(blank=True)),
                ('observed_at', models.DateField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rubric_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_records', to='assessments.rubriclevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='learners.student')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='cbc.learningoutcome')),
            ],
            options={
                'verbose_name': 'Evidence Record',
                'verbose_name_plural': 'Evidence Records',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['student', 'learning_outcome'], name='cbc_evidenc_student_9556ba_idx')],
            },
        ),
    ]
