# Generated by Django 6.0.1 on 2026-01-15 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('assessments', '0001_initial'),
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('evaluation_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('RUBRIC', 'Rubric'), ('DESCRIPTIVE', 'Descriptive')], default='NUMERIC', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('rubric_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='assessments.rubricscale')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='academic.subject')),
                ('term', models.ForeignKey(blank=True, help_text='Null for cross-term projects', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='academic.term')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Milestone',
                'verbose_name_plural': 'Project Milestones',
                'ordering': ['project', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_by', models.CharField(blank=True, max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='projects.project')),
                ('rubric_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_participations', to='assessments.rubriclevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participations', to='learners.student')),
            ],
            options={
                'verbose_name': 'Project Participation',
                'verbose_name_plural': 'Project Participations',
                'unique_together': {('project', 'student')},
            },
        ),
        migrations.CreateModel(
            name='MilestoneScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.CharField(blank=True, max_length=100)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='projects.projectmilestone')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_scores', to='projects.projectparticipation')),
            ],
            options={
                'verbose_name': 'Milestone Score',
                'verbose_name_plural': 'Milestone Scores',
                'unique_together': {('milestone', 'participation')},
            },
        ),
    ]
