# Generated by Django 6.0.1 on 2026-01-15 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_scales', to='academic.curriculum')),
            ],
            options={
                'verbose_name': 'Rubric Scale',
                'verbose_name_plural': 'Rubric Scales',
            },
        ),
        migrations.CreateModel(
            name='RubricLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('numeric_value', models.FloatField(help_text='For conversion/calculation')),
                ('sequence', models.PositiveSmallIntegerField(help_text='Display order')),
                ('rubric_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='assessments.rubricscale')),
            ],
            options={
                'verbose_name': 'Rubric Level',
                'verbose_name_plural': 'Rubric Levels',
                'ordering': ['rubric_scale', '-sequence'],
                'unique_together': {('rubric_scale', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assessment_type', models.CharField(choices=[('CAT', 'CAT'), ('TEST', 'Test'), ('MAIN_EXAM', 'Main Exam'), ('MOCK', 'Mock'), ('PROJECT', 'Project'), ('ASSIGNMENT', 'Assignment'), ('PRACTICAL', 'Practical'), ('COMPETENCY', 'Competency')], max_length=20)),
                ('evaluation_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('RUBRIC', 'Rubric'), ('DESCRIPTIVE', 'Descriptive'), ('COMPETENCY', 'Competency')], default='NUMERIC', max_length=20)),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('weight', models.FloatField(default=1.0, help_text='For final grade calculations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academic.subject')),
                ('term', models.ForeignKey(blank=True, help_text='Null for year-round CBC assessments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academic.term')),
                ('rubric_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='assessments.rubricscale')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('graded_by', models.CharField(blank=True, max_length=100)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='learners.student')),
                ('rubric_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_scores', to='assessments.rubriclevel')),
            ],
            options={
                'verbose_name': 'Assessment Score',
                'verbose_name_plural': 'Assessment Scores',
                'indexes': [models.Index(fields=['assessment', 'student'], name='assessments_assessm_349426_idx')],
                'unique_together': {('assessment', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['term', 'subject'], name='assessments_term_id_0b11fd_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assessment_date'], name='assessments_assessm_235491_idx'),
        ),
    ]
